services:
  - type: web
    name: finguard
    env: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: gunicorn run:app
    pythonVersion: 3.11.9

